# basic NSM model
CUDA_VISIBLE_DEVICES=0 python main_nsm.py --name CWQ --model_name gnn --data_folder /home/hegaole/data/KBQA/Freebase/CWQ/ --checkpoint_dir checkpoint/pretrain/ --batch_size 20 --test_batch_size 40 --num_step 4 --entity_dim 50 --word_dim 300 --kg_dim 100 --kge_dim 100 --eval_every 2 --experiment_name CWQ_nsm --eps 0.95 --num_epoch 100 --use_self_loop --lr 5e-4 --q_type seq --word_emb_file word_emb_300d.npy --reason_kb --encode_type --loss_type kl

# hybrid teacher student
CUDA_VISIBLE_DEVICES=0 python main_teacher.py --model_name gnn --teacher_type hybrid --data_folder /home/hegaole/data/KBQA/Freebase/CWQ/ --checkpoint_dir checkpoint/CWQ_teacher/ --batch_size 20 --test_batch_size 40 --num_step 4 --entity_dim 50 --word_dim 300 --kg_dim 100 --kge_dim 100 --eval_every 2 --experiment_name CWQ_hybrid_teacher --eps 0.95 --num_epoch 70 --use_self_loop --lr 5e-4 --q_type seq --word_emb_file word_emb_300d.npy --encode_type --loss_type kl --constrain_type js --reason_kb --lambda_constrain 0.01 --lambda_back 0.1 --load_experiment ../pretrain/CWQ_nsm-final.ckpt
CUDA_VISIBLE_DEVICES=0 python main_student.py --model_name gnn --teacher_model gnn --teacher_type hybrid --data_folder /home/hegaole/data/KBQA/Freebase/CWQ/  --checkpoint_dir checkpoint/CWQ_student/ --batch_size 20 --test_batch_size 40 --num_step 4 --entity_dim 50 --word_dim 300 --kg_dim 100 --kge_dim 100 --eval_every 2 --experiment_name CWQ_hybrid_student --eps 0.95 --num_epoch 100 --use_self_loop --lr 5e-4 --q_type seq --word_emb_file word_emb_300d.npy --reason_kb --encode_type --loss_type kl --constrain_type js --load_teacher ../CWQ_teacher/CWQ_hybrid_teacher-final.ckpt --lambda_label 0.05

# parallel teacher student
CUDA_VISIBLE_DEVICES=0 python main_teacher.py --model_name gnn --teacher_type parallel --data_folder /home/hegaole/data/KBQA/Freebase/CWQ/ --checkpoint_dir checkpoint/CWQ_teacher/ --batch_size 20 --test_batch_size 40 --num_step 4 --entity_dim 50 --word_dim 300 --kg_dim 100 --kge_dim 100 --eval_every 2 --experiment_name CWQ_parallel_teacher --eps 0.95 --num_epoch 30 --use_self_loop --lr 5e-4 --q_type seq --word_emb_file word_emb_300d.npy --encode_type --loss_type kl --constrain_type js --reason_kb --lambda_constrain 0.01 --lambda_back 0.1 --load_pretrain ../pretrain/CWQ_nsm-final.ckpt
CUDA_VISIBLE_DEVICES=0 python main_student.py --model_name gnn --teacher_model gnn --teacher_type parallel --data_folder /home/hegaole/data/KBQA/Freebase/CWQ/  --checkpoint_dir checkpoint/CWQ_student/ --batch_size 20 --test_batch_size 40 --num_step 4 --entity_dim 50 --word_dim 300 --kg_dim 100 --kge_dim 100 --eval_every 2 --experiment_name CWQ_parallel_student --eps 0.95 --num_epoch 100 --use_self_loop --lr 5e-4 --q_type seq --word_emb_file word_emb_300d.npy --reason_kb --encode_type --loss_type kl --constrain_type js --load_teacher ../CWQ_teacher/CWQ_parallel_teacher-final.ckpt --lambda_label 0.05

